export interface AttendeeModel {
  id?: string;  
  firstName: string,
  lastName: string,
  age: number,
  email?: string,
  invitedBy?: string,
  status?: string,
  address?: string,
  birthday?: string,
  facebookName?: string,
  facebookLink?: string,
  cellLeader?: string,
  primaryLeaderId?: string,
  network?: string,
  churchHierarchy?: string,
  memberStatus?: string,
  churchProcess?: string,
  gradeLevel?: string,
  section?: string,
  organizationId?: string,
  createdAt?: string,
  updatedAt?: string,
}
