export enum ChurchProcessEnum {
  NON_PESOL = 'NON_PESOL',
  CONSOLIDATION_PROCESS = 'CONSOLIDATION_PROCESS',
  START_UP_LESSON = 'START_UP_LESSON',
  PRE_ENCOUNTER = 'PRE_ENCOUNTER',
  POST_ENCOUNTER = 'POST_ENCOUNTER',
  UNDERCOVER = 'UNDERCOVER',
  SOL_1 = 'SOL_1',
  SOL_2 = 'SOL_2',
  SOL_3 = 'SOL_3',
  PASTORAL_MINISTRY = 'PASTORAL_MINISTRY',
}