export enum MemberStatusEnum {
  FIRST_TIMER = 'FIRST_TIMER',
  SECOND_TIMER = 'SECOND_TIMER',
  THIRD_TIMER = 'THIRD_TIMER',
  FOURTH_TIMER = 'FOURTH_TIMER',
  REGULAR_ATTENDEE = 'REGULAR_ATTENDEE',
  REGULAR_DISCIPLE = 'REGULAR_DISCIPLE',
  REGULAR_STARTUP = 'REGULAR_STARTUP',
  BACK_TO_LIFE = 'BACK_TO_LIFE',
  CELL_MEMBER = 'CELL_MEMBER',
  CHILDREN = 'CHILDREN',
}
